name: Prettier
on: [push, pull_request]

env:
    DATABASE_URL: "https://fake.com"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run Prettier
              run: npm run prettier
            - name: Typecheck
              run: npm run typecheck
            - name: Lint
              run: npm run lint
            - name: Print Environment Variable
              run: echo $MY_ENV_VAR