name: Prettier

on:
  push:
  pull_requiest:

env:
    DATABASE_URL: "https://fake.com"
	NODE_ENV: "development"
	UPLOADTHING_APP_ID: "some fake string"
	UPLOADTHING_SECRET: "some fake string"
	NEXT_PUBLIC_VISITORS_LINKS: "some fake string"
	NEXT_PUBLIC_UPLOADTHING_URL: "some fake string"
    CDEK_ID: "123"
	CDEK_SECRET: "321"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npm run prettier
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
